# =====================
# application-local.yml
# =====================

logging:
   level:
      root: warn
      com.rest.api: debug
      
spring:
   profiles: local
   datasource:
      url: jdbc:h2:tcp://localhost/~/test
      driver-calss-name: org.h2.Driver
      username: mytest
   jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      properties.hibernate:
         hbm2ddl.auto: update
         format_sql: true
      showSql: true
      generate-ddl: true
   url:
      base: http://localhost:8080
